name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      HYPRE_LIB_DIR: "/usr/lib/x86_64-linux-gnu/"
      HYPRE_INCLUDE_DIR: "/usr/include/hypre/"

    steps:
      - name: Setup hypre
        run: sudo apt install -y -q libhypre libhypre-dev
      - uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          override: true
      - name: Check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Lint
        uses: actions-rs/clippy-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- --no-deps # --D warnings
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test